FROM ubuntu:18.04

RUN apt-get update \
 && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg2 \
    software-properties-common \
    build-essential \
    cmake \
    git \
    libncurses5-dev \
    make \
    xz-utils \
    zlib1g-dev
